import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Food blog App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='Hi I am Saurabh,' message='I cook as a creative outlet to have outside of my 9-to-5.' />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  );
}
